# For compiling the add-on packages.
# $Id$

base64.elc: base64.el
	$(EMACS) -batch -f batch-byte-compile base64.el

format-spec.elc: format-spec.el
	$(EMACS) -batch -f batch-byte-compile format-spec.el

